version: '3'
services:

  backend:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 swarm_server.asgi:application
    ports:
      - '8000:8000'
    volumes:
      - backend_static:/backend/collectstatic
      - ./prod/db.sqlite3:/backend/db.sqlite3
      - ./prod/instagrapi/:/backend/instagrapi/
      - ./prod/audio/:/backend/swarm/static/audio/
      - ./prod/log/:/backend/log/

  huey:
    build: .
    command: python manage.py run_huey
    depends_on:
      - backend
    volumes:
      - ./prod/db.sqlite3:/backend/db.sqlite3
      - ./prod/instagrapi/:/backend/instagrapi/
      - ./prod/audio/:/backend/swarm/static/audio/
      - ./prod/log/:/backend/log/

  frontend:
    build: ./frontend
    volumes:
      - frontend_build:/frontend/build

  redis:
    image: docker.io/bitnami/redis:5.0.7
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/bitnami/redis/data

  nginx:
    image: nginx:latest
    ports:
      - '80:8080'
    volumes:
      - ./prod/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend_build:/var/www/frontend:ro
      - backend_static:/var/www/backend/static:ro
      - ./prod/audio/:/var/www/backend-media/static/audio:ro
    depends_on:
      - backend
      - frontend

volumes:
  frontend_build:
  backend_static:
  redis_data: