# Generated by Django 4.0.3 on 2022-03-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0002_media_run_delete_todo_media_reporter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='status',
        ),
        migrations.RemoveField(
            model_name='run',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='run',
            name='shown',
        ),
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.IntegerField(choices=[(0, 'Processing'), (1, 'Ready'), (2, 'Shown')], default=0),
        ),
    ]
