# Generated by Django 4.0.3 on 2022-03-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0003_remove_media_status_remove_run_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.IntegerField(choices=[(1, 'Photo'), (2, 'Video'), (8, 'Album')], default=1),
        ),
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.IntegerField(choices=[(1, 'Processing'), (2, 'Ready'), (3, 'Presenting'), (4, 'Complete')], default=0),
        ),
    ]
