# Generated by Django 4.0.3 on 2022-03-24 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0006_remove_media_date_execution_date_created_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Execution',
            new_name='InstagramAccount',
        ),
    ]
