# Generated by Django 4.0.3 on 2022-03-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0007_rename_execution_instagramaccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagramaccount',
            old_name='title',
            new_name='handle',
        ),
        migrations.AlterField(
            model_name='instagramaccount',
            name='status',
            field=models.IntegerField(choices=[(1, 'Processing'), (2, 'Ready')], default=1),
        ),
    ]
