# Generated by Django 4.0.3 on 2022-03-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0008_rename_title_instagramaccount_handle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=120)),
                ('status', models.IntegerField(choices=[(1, 'Processing'), (2, 'Ready'), (3, 'Presenting'), (4, 'Complete')], default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='instagramaccount',
            name='status',
            field=models.IntegerField(choices=[(1, 'Processing'), (2, 'Complete')], default=1),
        ),
    ]
