# Generated by Django 4.0.3 on 2022-03-24 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0010_rename_handle_session_title_instagramaccount_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='title',
            new_name='first_name',
        ),
    ]
