# Generated by Django 4.0.3 on 2022-03-24 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0011_rename_title_session_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='execution',
            new_name='account',
        ),
    ]
