# Generated by Django 4.0.3 on 2022-03-31 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0012_rename_execution_media_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramLoginAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
            ],
        ),
    ]
