# Generated by Django 4.0.4 on 2022-05-31 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0014_alter_media_options_media_audio_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='audio_filename',
            field=models.CharField(max_length=255),
        ),
    ]
