# Generated by Django 4.0.5 on 2022-06-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0015_alter_media_audio_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(-1, 'Ready, but no Audiostream clients are connected'), (1, 'Ready'), (2, 'Occupied')], default=-1)),
            ],
        ),
    ]
