# Generated by Django 4.0.5 on 2022-06-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0016_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='state',
            field=models.IntegerField(choices=[(1, 'Ready'), (2, 'Occupied')], default=-1),
        ),
    ]
