# Generated by Django 4.0.5 on 2022-06-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0018_state_date_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='date_ready',
            field=models.DateTimeField(blank=True),
        ),
    ]
