# Generated by Django 4.0.5 on 2022-06-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0020_alter_state_date_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='last_audio_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
