# Generated by Django 4.0.5 on 2022-06-23 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0021_state_last_audio_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='last_audio_name',
        ),
    ]
