# Generated by Django 4.0.5 on 2022-06-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0022_remove_state_last_audio_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='state',
            field=models.IntegerField(choices=[(1, 'Ready'), (2, 'Occupied'), (5, 'Processing')], default=1),
        ),
    ]
