# Generated by Django 4.0.5 on 2022-06-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0023_alter_state_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramloginaccount',
            name='first_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='instagramloginaccount',
            name='last_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.IntegerField(choices=[(1, 'Preprocessing'), (2, 'Waiting for follow'), (3, 'Processing'), (4, 'Ready'), (5, 'Complete'), (6, 'Error')], default=1),
        ),
    ]
