# Generated by Django 4.0.5 on 2022-06-24 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0024_instagramloginaccount_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='active_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swarm.session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.IntegerField(choices=[(1, 'Preprocessing'), (2, 'Waiting for follow'), (3, 'Processing'), (4, 'Presenting'), (5, 'Complete'), (6, 'Error')], default=1),
        ),
    ]
