# Generated by Django 4.0.6 on 2022-07-31 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0025_state_active_session_alter_session_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='swarm.instagramaccount'),
        ),
    ]
