# Generated by Django 4.0.6 on 2022-07-31 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0026_alter_media_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='swarm.instagramaccount'),
            preserve_default=False,
        ),
    ]
