# Generated by Django 4.0.6 on 2022-07-31 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0028_state_active_login_account_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='active_login_account_index',
        ),
    ]
