# Generated by Django 4.0.6 on 2022-07-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0029_remove_state_active_login_account_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramloginaccount',
            name='dont_use_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
