# Generated by Django 4.0.6 on 2022-08-01 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0030_instagramloginaccount_dont_use_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramloginaccount',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
