# Generated by Django 4.0.6 on 2022-08-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0032_instagramloginaccount_error_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.IntegerField(choices=[(1, 'Preprocessing'), (2, 'Waiting for follow'), (3, 'Processing'), (4, 'Presenting'), (5, 'Complete'), (6, 'Error'), (7, 'User interrupted')], default=1),
        ),
    ]
